#! /usr/bin/env ruby

require 'oauth'
require 'oauth/consumer'
require '/usr/bin/setting.rb'
require 'twitter'
require 'pp'

CONSUMER_KEY = "TvEDulP9wjxcAkpPS2r1ux4Fr"
CONSUMER_SECRET = "t3AO41ngBpr4I30I0bkYNFXXlQtjCwahAgNXoiEtYHkaWxtIcu"

client = Twitter::REST::Client.new do |config|
  config.consumer_key = CONSUMER_KEY
  config.consumer_secret = CONSUMER_SECRET
  config.access_token = ACCESS_TOKEN
  config.access_token_secret = ACCESS_TOKEN_SECRET
end

# Tweet
if ARGV[1]
  # Tweet by a certain client
elsif client.update(ARGV[0])
  puts "\e[36m♪ Tweeted\e[0m"
end
