#! /usr/bin/env ruby

require 'oauth'
require 'oauth/consumer'
require './config.rb'
require './setting.rb'
require 'twitter'
require 'pp'

client = Twitter::REST::Client.new do |config|
  config.consumer_key = CONSUMER_KEY
  config.consumer_secret = CONSUMER_SECRET
  config.access_token = ACCESS_TOKEN
  config.access_token_secret = ACCESS_TOKEN_SECRET
end

# Tweet
if client.update(ARGV[0])
  puts "\e[36m♪ Tweeted\e[0m"
end
