#! /usr/bin/env ruby

require 'oauth'
require 'oauth/consumer'
require 'twitter'
require 'pp'

require 'thor'

CONSUMER_KEY = "TvEDulP9wjxcAkpPS2r1ux4Fr"
CONSUMER_SECRET = "t3AO41ngBpr4I30I0bkYNFXXlQtjCwahAgNXoiEtYHkaWxtIcu"

class Twit < Thor
  default_command :twit

  desc "tweet", "t: Tweet by a certain account"
  def tweet(tweet='', account='') 
    require "/usr/bin/twit_setting_files/setting_file_#{account}"
    
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = CONSUMER_KEY
      config.consumer_secret = CONSUMER_SECRET
      config.access_token = ACCESS_TOKEN
      config.access_token_secret = ACCESS_TOKEN_SECRET
    end

    if client.update(tweet)
      puts "\e[36m♪ Tweeted\e[0m"
    end
  end

  desc 'list', 'l: Show a list of accounts'
  def list
    puts "\n---Accounts----" 
    accounts = Dir["/usr/bin/twit_setting_files/*"]
    accounts.each do |account|
      account.sub! '/usr/bin/twit_setting_files/setting_file_', ''
      account.sub! '.rb', ''
      puts account
    end
    puts "---------------" 
  end

end

Twit.start(ARGV)
